name: Docker Build and Deploy
on: [push, pull_request]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract branch name from git ref
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Push to Docker Hub (in Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: asdfasis/modoolist-server:${{ github.head_ref }}
      - name: Push to Docker Hub (in Master Push)
        if: ${{ github.event_name == 'push' &&
          steps.extract_branch.outputs.branch == 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: asdfasis/modoolist-server:latest

  pull_from_registry:
    name: Pull Docker Image and Run
    runs-on: ubuntu-latest
    needs: [push_to_registry]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Pull from Docker Hub and Run image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_password: ${{ secrets.SSH_PROXY_PASSWORD }}
          proxy_port: ${{ secrets.SSH_PROXY_PORT }}
          script: |
            docker pull asdfasis/modoolist-server:latest
            docker rm -f modoolist-server-prod
            docker run --name modoolist-server-prod --env-file /etc/modoolist-server.env -v /modoolist-files:/usr/src/app/exported-files -p 3000:3000 -d asdfasis/modoolist-server
